### ISSUE TITLE
partial H2FljB match

### ISSUE THREAD

**Issue by alantsangmb** [peterk87/sistr_cmd#22]
Hi Peter,

I am predicting an Salmonella isolate serotype using sistr.
I found that the wgs contig of my isolate only contain a partial match to fljB (920 bp in the 3' region out of the full 1521bp fljB gene)

But it still predict a serotype of Typhimurium with h2 1,2 predicted, I am wondering how the tool can assign the h2 antigen and the serotype. Is it based on the cgmlst phylogeny or partial blast match to fljB?

Following is the detail output:
cgmlst_ST	cgmlst_distance	cgmlst_matching_alleles	cgmlst_subspecies	h1	h2	o_antigen	serogroup	serovar	serovar_antigen	serovar_cgmlst
2633752927	0.015151515	325	enterica	i	1,2	4,[5],12	B	I 4,[5],12:i:-	Typhimurium	I 4,[5],12:i:-

Thanks.

**Comment by peterk87** [comment]
Hi @alantsangmb,

I've reformatted your table to make it a little easier to see what's going on:

| cgmlst_ST | cgmlst_distance | cgmlst_matching_alleles |  cgmlst_subspecies | h1 | h2 | o_antigen | serogroup | serovar | serovar_antigen | serovar_cgmlst |
| --- | --- | --- |  --- | --- | --- | --- | --- | --- | --- | --- |
| 2633752927 | 0.015151515 | 325 | enterica | i | 1,2 | 4,[5],12 | B | I 4,[5],12:i:- | Typhimurium | I 4,[5],12:i:- |

It looks like you may have a potential monophasic Typhimurium given the cgMLST distance of 0.015 to the nearest SISTR reference genome which has a serovar/antigenic formula of `I 4,[5],12:i:-`. Due to the similarity of your genome to the reference genome, the overall serovar prediction (under the `serovar` field) is `I 4,[5],12:i:-`. 

If you output more in-depth results, they could tell you if the H2 antigen is a real partial allele or found at the end of a contig (i.e. truncated). You can output the more in-depth results with the `-M` command-line option:

```
  -M, --more-results    Output more detailed results (-M) and all antigen
                        search blastn results (-MM)
```

Hope that helps you with interpreting the results you're getting with `sistr-cmd`!

**Comment by alantsangmb** [comment]
I see! Thank you so much for your explanation and help!
I am closing this issue.

**Comment by alantsangmb** [comment]
Sorry that I have a further question.

So for the column: | h1 | h2 | o_antigen | serogroup | serovar | serovar_antigen | serovar_cgmlst

which of them is the result directly predicted from the contigs and which column is the result deduced based on the similarity to the reference genome?

And what is the difference between serovar and serovar_cgmlst?
Thanks

**Comment by alantsangmb** [comment]
Just read into the funtion "is_blast_result_trunc" in the blast_wrapper code:

for this return true we have to fulfill the criteria:
(q_match_len < qlen) and (s_max >= slen or s_min <= 1)

it seems to me that (s_max >= slen or s_min <= 1) difficult to be true? as the contig is the subject and it could be very large? In my case, my smax (equivalent to send) is 1101 and while s_min is 182 and slen is 79006 . Should it refer to q_max, qmin and qlen instead?

**Comment by peterk87** [comment]
If the H2 antigen predictive fljB gene, is not truncated (i.e. is not found at the end of a contig) then you may have a real partial allele that may not express the phase 2 phenotype. In this case, the H2 prediction should probably be "-" rather than "1,2". We're interested in accurately predicting monophasic variants of different serovars like Typhimurium using `sistr-cmd`, and I'm actively working on improving the rules for H2 antigen prediction (and serovar prediction in general). So any suggestions are appreciated! 

> I am not very sure why the trunc values are false provided that the h2_fljb_prediction.top_result.length is 920 bp, what is the cutoff length to assign it to be trucated? 700bp?

`sistr-cmd` tries to extend the subject sequence match for the closest matching query sequence given the start and end positions of the query sequence.

So for example if you have a query that's 100bp with a match found of 90bp found in the subject sequence, then `sistr-cmd` will try to extend the subject sequence match by Xbp on the applicable end given the start and end positions of the query sequence. If the extension runs past an end of the subject sequence (e.g. past the end of a contig), then the result is flagged as `is_trunc = True`. 

So in the following code:

```python
(q_match_len < qlen) and (s_max >= slen or s_min <= 1)
```

- `s_max` is the theoretical extended max position of the subject sequence (can be greater than the subject sequence length)
- `s_min` is the theoretical extended min position of the subject sequence (can be less than 0)
- `q_len` is the query length
- `q_match_len` is the query sequence alignment length

The code for `is_trunc` and where `s_max` and `s_min` are calculated is found here:
https://github.com/peterk87/sistr_cmd/blob/master/sistr/src/blast_wrapper/__init__.py#L242


> And for the column: | h1 | h2 | o_antigen | serogroup | serovar | serovar_antigen | serovar_cgmlst
> Might I know which of them is the result directly predicted from the contigs and which column is the result deduced based on the similarity to the reference genome?
> And what is the difference between serovar and serovar_cgmlst?

- `serovar_antigen` is the prediction from the O- and H-antigen sequence matching alone 
- `serovar_cgmlst` is the prediction from cgMLST similarity to the closest matching reference genome
- `serovar` is the overall prediction from both the antigen search and cgMLST results. In some cases you will find that the antigen result is multiple serovars delimited by "|" (pipe), which denotes that the antigen based results are ambiguous and cannot definitively predict a single serovar designation. In this case, the cgMLST prediction can narrow down the serovar prediction to a single serovar. The cgMLST prediction overrides the antigen prediction in the case of a high similarity match to a reference genome (cgMLST distance <= 0.05). We've found that this hybrid approach works really well for producing accurate and robust serovar predictions. 

Hope that answers your questions! Let me know if you have any more questions :smiley:

**Comment by alantsangmb** [comment]
Thank you so much for your detailed and clear explanation. It is very helpful.  : )
